@githubAuth = githubapi
##### PRODUCTOVERVIEW

### Retrieves the list of products.
GET https://app-hrsei-api.herokuapp.com/api/fec2/hratx/products
Authorization: {{githubAuth}}

### Returns all product level information for a specified product id.
GET https://app-hrsei-api.herokuapp.com/api/fec2/hratx/products/12012
Authorization: {{githubAuth}}

### Returns the all styles available for the given product.
GET https://app-hrsei-api.herokuapp.com/api/fec2/hratx/products/12012/styles
Authorization: {{githubAuth}}

### Returns the id's of products related to the product specified.
GET https://app-hrsei-api.herokuapp.com/api/fec2/hratx/products/12012/related
Authorization: {{githubAuth}}

##### REVIEWS
POST https://app-hrsei-api.herokuapp.com/api/fec2/hratx/reviews
Authorization: {{githubAuth}}
Content-Type: application/json

{
    "product_id" : 12012,
    "rating": 5,
    "summary": "pies",
    "body": "pies",
    "recommend": true,
    "name": "pies",
    "email": "pies@pie.com",
    "photos":[],
    "characteristics":{}    
}